/** A text input message. */
export interface TextMessage { type: "input_text"; text: string }
/** An image input message. */
export interface ImageMessage { type: "input_image"; image_url: string }
/** A file input message. */
export interface FileMessage { type: "input_file"; file_url: string }
/** A message supplied as model input. */
export interface Message {
  type: "message";
  role: "user" | "assistant" | "developer" | "system";
  content: TextMessage | ImageMessage | FileMessage;
}
/** A function call supplied as model input. */
export interface FunctionCall { type: "function_call"; call_id: string; name: string; arguments: string }
/** The result of a previous function call. */
export interface FunctionCallOutput { type: "function_call_output"; call_id: string; output: string }
/** Any structured input accepted by NeuralLink. */
export type InputItem = Message | FunctionCall | FunctionCallOutput;
/** Optional model invocation settings. */
export interface Optional { instructions?: string }
/** Provider-neutral model invocation parameters. */
export interface NormalizedParams extends Optional { model: string; input: string | InputItem[] }
/** Lifecycle status of a model response. */
export type ResponseStatus = "completed" | "failed" | "in_progress" | "cancelled" | "queued" | "incomplete";
/** Text generated by the model. */
export interface TextContent { type: "output_text"; text: string }
/** A refusal generated by the model. */
export interface RefusalContent { type: "refusal"; refusal: string }
/** An assistant message emitted as a response output item. */
export interface OutputMessage {
  id?: string;
  type: "message";
  role: "assistant";
  content: TextContent | RefusalContent;
}
/** A single piece of model reasoning. */
export interface ReasoningText { type: "reasoning_text"; text: string }
/** A summary of model reasoning. */
export interface SummaryText { type: "summary_text"; text: string }
/** A reasoning response output item. */
export interface Reasoning {
  id?: string;
  type: "reasoning";
  content: ReasoningText;
  summary: SummaryText;
}
/** An output item produced by the model. */
export type ResponseOutputItem = OutputMessage | Reasoning;
/** Accumulated provider-neutral model response. */
export interface Response {
  id: string;
  created_at: number;
  status: ResponseStatus;
  output: ResponseOutputItem[];
}
/** Every provider-neutral event supported by NeuralLink. */
export type ResponseEvent =
  | { type: "response.created"; response: Response }
  | { type: "response.completed"; response: Response }
  | { type: "response.failed"; response: Response }
  | { type: "response.incomplete"; sequence_number: number; response: Response }
  | { type: "response.message_text.delta"; delta: string }
  | { type: "response.message_refusal.delta"; delta: string }
  | { type: "response.reasoning_summary_text.delta"; delta: string };
/** Converts between provider-specific and NeuralLink representations. */
export interface Converter<RequestParams, SourceEvent> {
  /**
   * Converts provider-neutral parameters into a provider request.
   * @param params Provider-neutral model parameters.
   * @returns The provider-specific request body.
   */
  toAPI(params: NormalizedParams): RequestParams;
  /**
   * Converts a provider event into a provider-neutral event.
   * @param event Provider-specific event data.
   * @param response The response accumulated before this event.
   * @returns One or more normalized response events, or undefined when unsupported.
   */
  fromEvent(event: SourceEvent, response: Response | undefined): ResponseEvent | ResponseEvent[] | undefined;
}
